### ISSUE TITLE
syncConfig: Irrelevant check against own values

### ISSUE THREAD

**Issue by robertwil** [boschglobal/locator_ros_bridge#10]
Hi,
if I'm not mistaken there is a bug checking for the configuration parameter:

Currently we are iterating through the **localization_client_rosconfig** (which is are the values from the ros parameter server set in the launch file) referencing its values to the **key** and **value** variables and then checking whether **key** exists in the "map" it is taken from, which does not really make sense.

```
void LocatorBridgeNode::syncConfig()
{
  ROS_INFO_STREAM("syncing config");
  XmlRpc::XmlRpcValue localization_client_rosconfig;
  nh_.getParam("localization_client_config", localization_client_rosconfig);

  auto loc_client_config = loc_client_interface_->getConfigList();
  // overwrite current locator config with ros params
  for (auto& iter : localization_client_rosconfig)
  {
    const auto& key = iter.first;
    auto& value = iter.second;
    if (!localization_client_rosconfig.hasMember(key))
    {
      ROS_WARN_STREAM("invalid locator rosparam found: " << key << ", " << value);
      continue;
    }
    ROS_INFO_STREAM("setting value for " << key << ", " << value);
```

I would therefore propose to check if **key** exists in the **loc_client_config** as you can see below (I assume that also was the plan initially ?). With this approach wrong variables are ignored and will not lead to a failure when calling   **loc_client_interface_->setConfigList(loc_client_config);** later on, which would then raise a runtime exception claiming "Invalid parameter". Not sure though if ".contains(key)" is the best approach for checking as I'm not to much into poco but it seems to work.

```
void LocatorBridgeNode::syncConfig()
{
  ROS_INFO_STREAM("syncing config");
  XmlRpc::XmlRpcValue localization_client_rosconfig;
  nh_.getParam("localization_client_config", localization_client_rosconfig);

  auto loc_client_config = loc_client_interface_->getConfigList();
  // overwrite current locator config with ros params
  for (auto& iter : localization_client_rosconfig)
  {
    const auto& key = iter.first;
    auto& value = iter.second;
    if (!loc_client_config.contains(key))
    {
      ROS_WARN_STREAM("invalid locator rosparam found: " << key << ", " << value);
      continue;
    }
    ROS_INFO_STREAM("setting value for " << key << ", " << value);
```

**Comment by slaible** [comment]
Yes you are right, the cat is biting its own tail here. I fixed it. Thank you!
