### ISSUE TITLE
Make angle units clear

### ISSUE THREAD

**Issue by robertwil** [boschglobal/locator_ros_bridge#11]
Hi,
while integrating the locator version 1.4 I found that the units of passed angles are not "consistent".

While it seems that when sending a seed pose the yaw angle is given in radians the locator apparently wants configurations like
`ClientSensor.laser.vehicleTransformLaser.yaw`
in degrees.

I could not find much information about this in the API Doc or the manual.
But is there a rule that the usual interfaces (binary and RPC) use radians and the configuration (configList / configSet) uses degree ?

**Comment by HWasserfuhr** [comment]
Hello @robertwil, thanks for pointing this out.

We will add a more detailed explanation for unclear angle units in the Locator API documentation (plus some explanatory comments in the ROS Bridge code).
We will also discuss internally if there is a reason for the angle units not being consistent and possibly fix this.
