### ISSUE TITLE
Release fixes for noetic

### ISSUE THREAD

**Issue by robertwil** [boschglobal/locator_ros_bridge#12]
Hi,

while the errors inside the release 1.0.5 (16.02.) were already fixed on noetic (e.g. #9) they were not released, so the downloadable package does not work with any locator version.

Could you please release the latest commits ? I hope this works with your internal development/release strategy.

**Comment by slaible** [comment]
Hi @robertwil,

I just triggered a release 1.0.6. When it will be available depends on ROS, or rather on the OSRF (Open Source Robotics Foundation). We have no influence on that, and this can take up to a month. You can check the current version with `apt show ros-noetic-bosch-locator-bridge`.
However, there will be a new release for Locator v1.5 soon anyway, which will not be compatible with Locator v1.4.
