### ISSUE TITLE
Bridge I/O error after erroneous scan 

### ISSUE THREAD

**Issue by robertwil** [boschglobal/locator_ros_bridge#14]
Hi,

I'm currently testing with a different scanner (P&F R2000, with a ROS driver) which seems to not work at all (can't access scan from any state).
In the aXessor the Diagnostic complains about :
- Sensor laser has failed
- Sensor laser report error multiple invalid scans received
So I assume that some fields in the scan do not fit the expectation.

In the node I get the continuous output:
`[ INFO] [1651750958.149401246]: initialization done
[ INFO] [1651750958.206198200]: accepted connection from 172.53.0.4:58912 at 172.53.0.3:4242
[ INFO] [1651750958.313557561]: 28883 bytes successfully sent via 172.53.0.3:4242
[ INFO] [1651750960.250646928]: accepted connection from 172.53.0.4:58914 at 172.53.0.3:4242
[ERROR] [1651750960.277708102]: caught io exception: I/O error  -  I/O error
[ WARN] [1651750960.278207477]: discarding 1 connections!
[ INFO] [1651750960.860000941]: accepted connection from 172.53.0.4:58916 at 172.53.0.3:4242
[ERROR] [1651750960.912654091]: caught io exception: I/O error  -  I/O error
[ WARN] [1651750960.912805547]: discarding 1 connections!
[ INFO] [1651750962.867032249]: accepted connection from 172.53.0.4:58918 at 172.53.0.3:4242
[ERROR] [1651750962.911561683]: caught io exception: I/O error  -  I/O error
[ WARN] [1651750962.911672637]: discarding 1 connections!
[ INFO] [1651750963.459224024]: accepted connection from 172.53.0.4:58920 at 172.53.0.3:4242
[ERROR] [1651750963.517211433]: caught io exception: I/O error  -  I/O error
[ WARN] [1651750963.517338002]: discarding 1 connections!
[ INFO] [1651750965.487194223]: accepted connection from 172.53.0.4:58922 at 172.53.0.3:4242
[ERROR] [1651750965.544421104]: caught io exception: I/O error  -  I/O error`

The scan looks like this:
header: 
  seq: 10406
  stamp: 
    secs: 1650891195
    nsecs: 646530015
  frame_id: "r2000"
angle_min: -3.1415927410125732
angle_max: 3.1415927410125732
angle_increment: 0.001745329238474369
time_increment: 7.936508154671174e-06
scan_time: 0.02857142873108387
range_min: 0.0
range_max: 200.0
ranges: [0.12200000137090683, 0.12600000202655792, 0.13899999856948853, 0.12800000607967377, 0.13300000131130219, **[...]** 1048.574951171875, 1048.574951171875, **[...]**
intensities: [228.0, 226.0, 226.0, 227.0, 228.0, 225.0, 224.0, 225.0, 224.0, 222.0, 218.0, 218.0, 217.0, 213.0, 211.0, 207.0, 207.0, 203.0, 201.0, 202.0, 195.0, 192.0, 189.0, 182.0, 179.0, 174.0, 174.0, 174.0, 169.0, 168.0, 169.0, 171.0, 167.0, 175.0, 177.0, 180.0, 185.0, 186.0, 187.0, 189.0, 192.0, 193.0, **[...]**

I noticed that angle_min and angle_max both are slightly bigger than PI and there are ranges much bigger than range_max (I guess this one should be no problem).

The frequency is 35Hz. I get 3600 ranges and intensities.RVIZ or any other ROS node used did not complain.

Do you have any idea what could be the issue here ?
Do I have any chance to see a more exact description of the problem (in docker logs ?) ?
If it's not clear I can also try to upload a stripped version of the used rosbag containing the message.

Best regards
Robert

**Comment by slaible** [comment]
Hi Robert,
the Locator is actually very precise when it comes to `angle_increment`. Could you set it to the exact value `(angle_max - angle_min) / (ranges.size - 1)`? Otherwise having a short bag file, I could have a look.

**Comment by robertwil** [comment]
Thanks for the quick response.
setting
`msg.angle_max - msg.angle_min) / (msg.ranges.size() - 1)`
seems to have fixed the issue.
I would not have guessed this as the difference is just 4.850104906618802e-07 .

Is there any way to catch this in the bridge ? E.g. directly setting it this way and not using the msg.angle_increment ?
Do you know how it's handled by the bosch locator container ? Does it check whether (angle_max - angle_min) / (ranges.size - 1) equals angle_increment and then discard the whole scan ?

**Comment by slaible** [comment]
Yes, the whole scan is discarded when the requirements are not met. How to handle this in the bridge is not clear, since we do not know whether `angle_min`, `angle_max` or `angle_increment` is wrong; although with such small differences this probably does not make a big difference.
But a meaningful error message in the bridge would be useful in any case. In fact, I've already started this in https://github.com/boschglobal/locator_ros_bridge/commits/feature/check-why-sending-scan-failed

**Comment by robertwil** [comment]
Outputting a error message will surely be useful to judge more quickly what's the problem. Then the developer of the driver for the  scanner should be contacted rather than assuming what's wrong and correcting fields here in the bridge.
I think it's only important, that the same check mechanism is used here as in the locator client.

**Comment by slaible** [comment]
Output of a meaningful error message for invalid scans implemented for all ROS distributions for Locator v1.5.
