### ISSUE TITLE
Support arrays in config

### ISSUE THREAD

**Issue by robertwil** [boschglobal/locator_ros_bridge#19]
Hi,
trying to upload arrays as config parameters (e.g.  for laser masking) is currently unsupported.
I'm not sure why it was left out as there's already a TODO for it:
https://github.com/boschglobal/locator_ros_bridge/blob/89ccb93d60cda6162ed02fbfe9477e18a30c0f6e/bosch_locator_bridge/src/locator_bridge_node.cpp#L398

I guess it should be sufficient to add
```
case XmlRpc::XmlRpcValue::TypeArray:
        loc_client_config[key] = static_cast<std::array>(value);
        break;

```

Were there any problems doing this or was it simply never used and therefore left out ?

**Comment by slaible** [comment]
Hi, yes it would make sense to support arrays. It is a bit more complicated than the code snippet you provided, because the array elements can be of different type. I'll have to take a look at how to do that.
