### ISSUE TITLE
bosch_locator_bridge_utils dependency nav2_util missing in Rolling 

### ISSUE THREAD

**Issue by nuclearsandwich** [boschglobal/locator_ros_bridge#36]
The [source package builds](https://build.ros2.org/view/Rbin_uJ64/job/Rsrc_uJ__bosch_locator_bridge_utils__ubuntu_jammy__source/) for `bosch_locator_bridge_utils` are currently failing for this package due to the lack of bloom artifacts for this package on Rolling.

When running bloom-release, the maintainer is warned of this with a message like the following, which they must explicitly override.

```
Could not resolve rosdep key 'nav2_util'
Failed to resolve nav2_util on ubuntu:jammy with: Error running generator: Failed to resolve rosdep key 'nav2_util', aborting.
nav2_util is depended on by these packages: ['bosch_locator_bridge_utils']
<== Failed
Some of the dependencies for packages in this repository could not be resolved by rosdep.
<== The following generator action reported that it is missing one or more
    rosdep keys, but that the key exists in other platforms:
'['/home/steven/osrf/bloom/.direnv/python-3.10.10/bin/git-bloom-generate', '-y', 'rosdebian', '--prefix', 'release/rolling', 'rolling', '-i', '2', '--os-name', 'ubuntu']'
```

However, as a result, release artifacts for neither `bosch_locator_bridge` and `bosch_locator_bridge_utils` are generated and neither package can build on the build farm.

Since the override was performed, I am assuming that this failure is expected. To stop automated emails when this package tries to build, I am going to block future attempts to build it on the build farm.

If nav2_util becomes available on Rolling in the future, then the block can be lifted.

It would also be possible to suppress the package in rolling by adding a `rolling.ignored` file to the bloom release repository. That may be a preferable solution since it would also prevent these prompts from popping up for each release and would unblock `bosch_locator_bridge` on the build farm in Rolling.

**Comment by nuclearsandwich** [comment]
I've opened https://github.com/ros2-gbp/locator_ros_bridge-release/pull/2 which would block the affected package from bloom generation and hopefully unblock `bosch_locator_bridge`.

**Comment by slaible** [comment]
Hi @nuclearsandwich, since I do not expect `nav2_util` to be released for Rolling any time soon, I also think this is the way to go. I just did not know how to ignore a package like that. Thanks a lot!!

**Comment by slaible** [comment]
I merged the above PR, the issue can be closed.
