### ISSUE TITLE
tf Broadcaster

### ISSUE THREAD

**Issue by tessa-j** [boschglobal/locator_ros_bridge#41]
Hi,

in a previous PR, the tf broadcaster that published the transform between localization pose and map fram was removed: 
https://github.com/boschglobal/locator_ros_bridge/pull/21
Unfortunately there was no comment on the reason for the removal?

The tf message was important for our development. I am therefore suggesting to re-introduce a tf broadcaster.
I already added the boadcaster to my local copy of the localor bridge, and would offer to create a PR with my changes.
If there are strong reasons why there should be no such broadcaster, I suggest we can discuss this here. 

Best,
Tessa

**Comment by slaible** [comment]
Hi @tessa-j,

We removed the TF broadcaster for two reasons. First of all it is a bit beyond the scope of the bridge, which only converts data types. And second, the correct way in ROS is to broadcast the transform between the `map` and the `odom` frame. Therefore, this is now done in a separate node, however, only in the master branch: https://github.com/boschglobal/locator_ros_bridge/blob/8bf9a5833447cd8f910a9325be7a12b0956b6644/bosch_locator_bridge_utils/src/locator_node.cpp#L199

If we were to decide to reintroduce it, I would suggest being able to turn this on and off with a parameter; and that parameter would default to false.

**Comment by tessa-j** [comment]
Hi @slaible,
If we can set this parameter in the launchfile, the separate node sounds like a viable solution for us. 
I assume the node publishes the transform between map and base_laser as the bridge did before?
Could you make this node availabe on the noetic-v1.7 branch as well?

**Comment by slaible** [comment]
The node publishes the transform between map and odom, and it is Nav2 / ROS 2 specific.
