### ISSUE TITLE
Transform from map to odom seems not right

### ISSUE THREAD

**Issue by thkfighter** [boschglobal/locator_ros_bridge#56]
### Environment
locator_ros_bridge branch humble
ROKIT Locator 1.8.3
Ubuntu 22.04

### Messages
```
$ ros2 topic echo /tf
---
transforms:
- header:
    stamp:
      sec: 1706858883
      nanosec: 601077248
    frame_id: map
  child_frame_id: odom
  transform:
    translation:
      x: -0.0
      y: -0.0
      z: -0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---

$ ros2 topic echo /bridge_node/client_localization_pose/pose
---
header:
  stamp:
    sec: 1706861375
    nanosec: 198044416
  frame_id: map
pose:
  pose:
    position:
      x: 0.8653682942296593
      y: 1.2231534096648244
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.016088766305604588
      w: 0.9998705674229859
  covariance:
  - 2.2153023087347317e-06
  - -1.4159173185142234e-07
  - 0.0
  - 0.0
  - 0.0
  - -6.722669799295493e-09
  - 0.0
  - 2.0820756349258835e-06
  - 0.0
  - 0.0
  - 0.0
  - 7.752037966660419e-08
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 9.668179363051017e-08
---
```
### Screenshots
RViz
![RViz_no_tf_of_map2odom_Screenshot from 2024-02-02 16-11-32](https://github.com/boschglobal/locator_ros_bridge/assets/28823037/7482a700-4c66-4dba-b608-e3af5a7d1bda)
rosgraph
![rosgraph](https://github.com/boschglobal/locator_ros_bridge/assets/28823037/7e02dc79-cbd3-4552-8b04-18930db64e95)
![aXessor_Screenshot from 2024-02-02 16-22-39](https://github.com/boschglobal/locator_ros_bridge/assets/28823037/f997342a-bdb3-4167-afb8-7c9d24688a76)

**Comment by kfabian** [comment]
The locator_node from the bosch_locator_bridge_utils packages is designed to replace the amcl node from Navigation2 and  provide a transformation from the `map` frame to the `odom` frame. That means the transformation from `map` to `odom` is correcting the error of the `odom` to `base_footprint` transformation, which should be provided by the vehicle odometry. From the rosgraph you attached, I would guess that there is no `odom` to `base_footprint` transformation provided. If you can not provide this transformation, you should be able to work around this by either providing an identity transformation for `odom` to `base_footprint` using tf2s `static_transform_publisher` or by setting the [`odom_frame_id`](https://github.com/boschglobal/locator_ros_bridge/blob/b4a60ff998d0c36fc6fd78dcd5f90e28215d564a/bosch_locator_bridge_utils/params/params.yaml#L6) parameter to `base_footprint`.

**Comment by thkfighter** [comment]
These two methods both work. Thanks, @kfabian .
![transform_from_map_to_base_footprint_Screenshot from 2024-02-09 00-23-39](https://github.com/boschglobal/locator_ros_bridge/assets/28823037/2d6e6101-8f56-4b31-ba48-997fb20a8b60)
